module.exports = [
  {
    name: "Salmon Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/salmon_asparagus.png",
    price: 6.5,
    qty: 50,
    calories: 512,
    nutrition: {
      carbohydrates: "12",
      fat: "23",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "30",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "olive oil"],
    toppings: ["lemon", "pepper"],
  },
  {
    name: "Salmon Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/salmon_salad.png",
    price: 6.0,
    qty: 25,
    calories: 438,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "20",
      protein: "30",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "carrot", "cherry tomatoes", "olive oil", "kale"],
    toppings: ["lemon", "pepper"],
  },
  {
    name: "Grilled Chicken Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/grilled_chicken_asparagus.png",
    price: 6.5,
    qty: 50,
    calories: 568,
    nutrition: {
      carbohydrates: "10",
      fat: "20",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "30",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["chicken breast", "asparagus", "parsley", "olive oil"],
    toppings: ["lemon", "pepper"],
  },
  {
    name: "Fruit Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/fruit_salad.png",
    price: 3.5,
    qty: 25,
    calories: 188,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "5",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["kiwi", "strawberries", "walnuts"],
    toppings: ["black raspberries", "blue berries"],
  },
  {
    name: "Fruit & Nut Cereal",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/fruit_nut_cereal.png",
    price: 3.5,
    qty: 50,
    calories: 343,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["cereal", "strawberries", "banana", "chocolate"],
    toppings: ["black raspberries", "coconut flakes", "blue berries"],
  },
  {
    name: "Fruit Cereal",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/fruit_cereal.png",
    price: 3.5,
    qty: 25,
    calories: 256,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["strawberries", "banana", "cereals", "yoghurt"],
    toppings: ["almond nuts", "chia seeds", "chocolate chips"],
  },
  {
    name: "Fig & Kiwi Yoghurt",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/fig_kiwi_yoghurt.png",
    price: 4.5,
    qty: 50,
    calories: 222,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["dried figs", "kiwi", "yoghurt"],
    toppings: ["mint leaves", "cherries", "black berries", "lemon"],
  },
  {
    name: "Dragon Smoothie Bowl",
    description:
      "In a blender, combine the pitaya, banana, almond milk, and coconut butter and puree until smooth. Pour into a bowl and add any fruits toppings as desired. You can purchase pitaya fresh or frozen. It’s available in frozen single-serving smoothie packs.",
    img: "/images/dragon_smoothie_bowl.png",
    price: 4.5,
    qty: 25,
    calories: 215,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["frozen pitaya", "banana", "almond milk", "coconut butter"],
    toppings: ["coconut flakes", "strawberries", "granola", "walnut", "kiwi"],
  },
  {
    name: "Avocado & Three Beans Salad",
    description:
      "I know so many of us are accustomed to the classic three bean salad with green beans, garbanzos and kidney beans made with a tangy vinaigrette. This recipe adds some southwest flair to the mix or maybe it’s Tex-Mex in its own way. The avocado really stands out in this particular salad.",
    img: "/images/avocado_beans.png",
    price: 3.5,
    qty: 50,
    calories: 235,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["Avocado", "kernel corn", "chickpeas", "olive oil", "kale"],
    toppings: ["lemon", "chia seeds", "sesame seeds"],
  },
  {
    name: "Baked Salmon Quinoa",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/baked_salmon_quinoa.png",
    price: 6.5,
    qty: 25,
    calories: 489,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "quinoa", "olive oil", "avocado"],
    toppings: ["lemon", "parsley", "dal"],
  },
  {
    name: "Chicken Breast & Veggies",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/breast_meat_veggie.png",
    price: 6.5,
    qty: 25,
    calories: 526,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["chicken breast", "broccoli", "cauliflower", "carrots"],
    toppings: ["red pepper bell", "parsley", "lemon"],
  },
  {
    name: "Spring Quinoa Bowl",
    description:
      "This simple and healthy quinoa bowl is the perfect meal for spring!",
    img: "/images/spring_quinoa_bowl.png",
    price: 3.5,
    qty: 25,
    calories: 388,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: [
      "avocado",
      "hard boiled eggs",
      "asparagus",
      "quinoa",
      "arugula",
    ],
    toppings: ["almond nuts", "peas", "raddish"],
  },
  {
    name: "Arugula & Chickpea Salad",
    description:
      "Hearty, protein-rich chickpeas combined with the rich, peppery flavour of arugula, tangy feta, and dressed with a tangy lemon-dill vinaigrette. This light and healthy Greek Chickpea Arugula Salad is the perfect transition recipe from winter to spring!",
    img: "/images/arugula_chickpea_salad.png",
    price: 2.5,
    qty: 25,
    calories: 416,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["arugula", "dried figs", "chickpeas", "tarragon"],
    toppings: ["lemon", "feta cheese", "cucumber", "almond nuts"],
  },
];
