module.exports = [
  {
    name: "Salmon Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/salmon_asparagus.jpg",
    price: 0.5,
    qty: 50,
    calories: 199,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/salmon_salad.png",
    price: 1.5,
    qty: 25,
    calories: 188,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/salmon_asparagus.jpg",
    price: 0.5,
    qty: 50,
    calories: 199,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/salmon_salad.png",
    price: 1.5,
    qty: 25,
    calories: 188,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/salmon_asparagus.jpg",
    price: 0.5,
    qty: 50,
    calories: 199,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/salmon_salad.png",
    price: 1.5,
    qty: 25,
    calories: 188,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/salmon_asparagus.jpg",
    price: 0.5,
    qty: 50,
    calories: 199,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/salmon_salad.png",
    price: 1.5,
    qty: 25,
    calories: 188,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Asparagus",
    description:
      "Loaded with protein, healthy fats, and some veggies, you only need 6 ingredients to whip together this simple salmon recipe. Just 5 minutes of prep time and 8 minutes of cook time and everything can be cooked in one go using your air fryer.",
    img: "/images/salmon_asparagus.jpg",
    price: 0.5,
    qty: 50,
    calories: 199,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
  {
    name: "Salmon Salad",
    description:
      "This dish makes a main dish salad with chopped vegetables, flaky fish, and tangy citrus dressing. It has plenty of protein and healthy fats, so it’s nutritious and delicious! Make this for dinner tonight for as a lunch meal prep for the week!",
    img: "/images/salmon_salad.png",
    price: 1.5,
    qty: 25,
    calories: 188,
    nutrition: {
      carbohydrates: "10",
      fat: "10",
      cholesterol: "10",
      sodium: "10",
      potassium: "10",
      protein: "10",
    },
    vitamins: {
      a: "10",
      b12: "10",
      b6: "10",
      c: "10",
      d: "10",
      e: "10",
    },
    ingredients: ["salmon", "asparagus", "parsley", "lemon juice", "olive oil"],
  },
];
